# Project-wide Gradle settings for Android subproject.
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# AndroidX flags
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Performance optimizations
org.gradle.parallel=true
org.gradle.caching=true
